---
title: "Atividade_Pratica_2"
author: "Tiago Evangelista Pardo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Bibliotecas
```{r}
library(tidyverse)
library(readxl)
library(stringi)
library(factoextra)
library(ggrepel)
```

# Importando dados
```{r}
dados <- read_xlsx("produtividade_policial.xlsx")

dados %>% 
  sample_n(10)
```
# Tratando dados

## Removendo carcteres especiais

```{r}
dados <- dados %>% 
  rename_with(~ stri_trans_general(.x, "Latin-ASCII") %>% 
                tolower())
```


## Removendo coluna "Total"

```{r}
dados <- dados[, -which(names(dados) == 'total')]
dados
```


## Pivotando tabela - meses para coluna


```{r}
dados1 <- dados %>%
          pivot_longer(
            cols = -c(ocorrencia, regiao),
            names_to = 'mes',
            values_to = 'casos'
  )
```


```{r}
dados1 <- dados1 %>% 
          pivot_wider(names_from = 'ocorrencia',
                      values_from = 'casos')

```


